services:
    arcaea-potential:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        init: true
        container_name: arcaea-potential
        working_dir: /workspace
        volumes:
            - ./:/workspace
            - node-modules:/workspace/node_modules
        tty: true

volumes:
    node-modules:
