@startuml Notes

abstract class "Notes(ノーツ数)" as Notes {
    + value: integer
}

class "SongNotes(曲ノーツ数)" as SongNotes {
}

class "PureNotes(Pureノーツ数)" as PureNotes {
}

class "ShinyPureNotes(内部ノーツ数)" as ShinyPureNotes {
}


Notes <-up- SongNotes
Notes <-up- ShinyPureNotes
Notes <-up- PureNotes

note bottom of SongNotes
    MAX = 1
    MIN = 2236 (PMを取らずに10,000,000を超えない最大ノーツ数)
end note

note bottom of PureNotes
    MAX = 0 (0ノーツでもよい)
    MIN = 2236
end note

note bottom of ShinyPureNotes
    MAX = 0
    MIN = 2236
end note

@enduml
