@startuml Score

!include ./grade/grade.pu

class "Score(スコア)" as Score {
    + value: number
    ---
    + scoreGrade(): Grade
    + scorePotential(): Potential
}

note bottom of Score {
    MIN = 0
    MAX = 10010000 (余裕をもって、PMスコア + 10000)

    songGradeはEX+までを返す
}

Score -down- Grade

@enduml
