@startuml BookAggregation

title 楽曲

package "楽曲(Song)" {

    !include ./songId/songId.pu
    !include ./songData/songData.pu
    !include ./pack/pack.pu
    !include ./side/side.pu
    !include ./version/version.pu
    !include ./difficultyData/difficultyData.pu
    !include ./score/score.pu

    class "Song(楽曲)" as Song << (R,red) RootEntity >> {
        SongId: SongId
        SongData: 楽曲情報
        Pack: パック
        Side: 属性
        Version: バージョン
        DifficultyData: 難易度情報
        Score: スコア
        ---
        isDeleted()
        hitPureNotes()
        hitShinyPureNotes()
    }

    Song *-down- SongId
    Song *-down- SongData
    Song *-down- Pack
    Song *-down- Side
    Song *-down- Version
    Song *-down- DifficultyData
    Song *-down- Score
}

@enduml
