@startuml Song

title 楽曲

package "楽曲(Song)" {

    !include ./songId/songId.pu
    !include ./songData/songData.pu
    !include ./songMetadata/songMetadata.pu
    !include ./difficulty/difficulty.pu
    !include ./chartData/chartData.pu
    !include ./score/score.pu
    !include ./potential/potential.pu

    class "Song(楽曲)" as Song << (R,red) RootEntity >> {
        SongId: SongId
        SongData: 楽曲情報
        SongMetadata: メタデータ
        Difficulty: 難易度
        ChartData: 難易度情報
        ---
        + create(): Song
        isDeleted(): boolean
        hitPureNotes(): PureNotes
        hitShinyPureNotes(): ShinyPureNotes
        scoreGrade(): Grade
        obtainPotential(): Potential
    }

    Song *-down- SongId
    Song *-down- SongData
    Song *-down- SongMetadata
    Song *-down- Difficulty
    Song *--down-- ChartData
    Song *-down- Score
    Song -down- Potential
}

@enduml
