@startuml DifficultyName

class "DifficultyName(難易度名)" as DifficultyName {
    + value: DifficultyEnum
}

enum "DifficultyEnum" as DifficultyEnum {
    PAST: PST
    PRESENT: PRS
    FUTURE: FTR
    BEYOND: BYD
    ETERNAL: ETR
}

DifficultyName *-down- DifficultyEnum

@enduml
