@startuml Difficulty

!include ./difficultyName/difficultyName.pu
!include ./level/level.pu

class "Difficulty(難易度)" as Difficulty {
    + name: DifficultyName
    + level: Level
}

Difficulty *-down- DifficultyName
Difficulty *-down- Level

@enduml
